import { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import {
  Printer, ArrowLeft, AlertTriangle, FlaskConical, Activity, ImageOff,
} from 'lucide-react';
import { screeningService } from '../../services/entities.service';
import { resolveMediaUrl } from '../../services/api';
import { getRiskMeta } from '../../utils/riskConfig';
import Button from '../../components/ui/Button';
import Skeleton from '../../components/ui/Skeleton';
import EmptyState from '../../components/ui/EmptyState';
import toast from 'react-hot-toast';

/**
 * Printable clinical report for a single screening.
 *
 * This is the one screen whose output leaves the system on paper and ends up
 * in a patient file, so it is held to a stricter standard than the in-app
 * views: nothing appears here that the record does not actually contain.
 *
 * Three things it deliberately refuses to do:
 *
 *   - Draw a heatmap that isn't one. The previous version rendered
 *     originalImageUrl twice and painted a fixed CSS radial-gradient over the
 *     second copy, labelled "Grad-CAM Pathological Heatmap". Every report
 *     showed identical red blobs in the same two spots regardless of the
 *     image, and a clinician reading the printout had no way to know.
 *
 *   - Print a synthetic screening. Records flagged isMock came from the
 *     development stub and contain nothing about the patient.
 *
 *   - Show a severity for an ungradable image, where the model produced no
 *     classification at all.
 */

const PROBABILITY_ROWS = [
  { key: 'noDR', label: 'No DR' },
  { key: 'mild', label: 'Mild NPDR' },
  { key: 'moderate', label: 'Moderate NPDR' },
  { key: 'severe', label: 'Severe NPDR' },
  { key: 'proliferative', label: 'Proliferative DR' },
];

export default function ReportViewer() {
  const { id } = useParams();
  const [screening, setScreening] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;

    const fetchScreening = async () => {
      try {
        const res = await screeningService.getById(id);
        if (!cancelled) setScreening(res.data.screening);
      } catch {
        if (!cancelled) toast.error('Failed to load screening record for report');
      } finally {
        if (!cancelled) setLoading(false);
      }
    };

    fetchScreening();
    return () => {
      cancelled = true;
    };
  }, [id]);

  if (loading) {
    return (
      <div className="p-8 max-w-4xl mx-auto space-y-6">
        <Skeleton count={3} variant="card" />
      </div>
    );
  }

  if (!screening) {
    return (
      <div className="p-8 max-w-md mx-auto">
        <EmptyState
          icon={Activity}
          title="Report not found"
          description="The clinical report could not be compiled."
          action={
            <Link to="/screenings" className="text-xs text-cyan-400 hover:underline">
              Back to screenings
            </Link>
          }
        />
      </div>
    );
  }

  // A synthetic record must never be printable as a clinical document.
  if (screening.isMock) {
    return (
      <div className="p-8 max-w-lg mx-auto">
        <div className="rounded-3xl border border-red-500/40 bg-red-950/40 p-6 space-y-3">
          <div className="flex items-center gap-2.5">
            <FlaskConical className="w-5 h-5 text-red-400" />
            <h1 className="text-sm font-bold text-red-100">
              No report can be issued for this screening
            </h1>
          </div>
          <p className="text-xs text-red-200/90 leading-relaxed">
            This record was generated by the development stub rather than the AI model. It
            contains no information about this patient&apos;s retina, so it cannot be compiled
            into a clinical report.
          </p>
          <Link to="/screenings" className="inline-block text-xs text-cyan-400 hover:underline">
            Back to screenings
          </Link>
        </div>
      </div>
    );
  }

  const isUngradable = screening.analysisStatus === 'ungradable' || !screening.prediction;
  const riskMeta = getRiskMeta(screening.prediction);
  const patient = screening.patient || {};
  const prob = screening.probabilities || {};
  const quality = screening.imageQuality || {};
  const uncertainty = screening.uncertainty || {};

  const originalUrl = resolveMediaUrl(screening.originalImageUrl);
  const heatmapUrl = resolveMediaUrl(screening.heatmapImageUrl);

  // Organisation comes from the record, not the markup. Hardcoding it meant
  // every deployment printed the same letterhead.
  const organisation =
    patient.organizationName || screening.screeningCamp?.name || 'RetinaAI Screening Programme';

  const screenedOn = screening.createdAt
    ? new Date(screening.createdAt).toLocaleString()
    : 'Not recorded';

  return (
    <div className="p-4 sm:p-8 max-w-4xl mx-auto space-y-6">
      {/* Action bar — never printed */}
      <div className="print:hidden flex items-center justify-between glass-panel p-4 rounded-3xl border border-slate-800 shadow-xl">
        <Link
          to={`/screenings/${screening._id}`}
          className="flex items-center gap-2 text-xs font-bold text-slate-300 hover:text-white transition"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to screening
        </Link>
        <Button variant="cyan" onClick={() => window.print()}>
          <Printer className="w-3.5 h-3.5" />
          Print report
        </Button>
      </div>

      <div className="bg-slate-950 p-8 sm:p-12 rounded-3xl border border-slate-800 shadow-2xl print:border-0 print:shadow-none print:p-0 print:bg-white print:text-slate-900 space-y-8 text-slate-100">
        {/* Letterhead */}
        <div className="flex items-start justify-between border-b-2 border-slate-800 print:border-slate-900 pb-6">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 bg-gradient-to-br from-cyan-500 to-blue-600 rounded-2xl flex items-center justify-center text-slate-950 font-black shadow-md print:bg-blue-600 print:text-white">
              RA
            </div>
            <div>
              <h1 className="text-2xl font-black tracking-tight text-white print:text-slate-900">
                RetinaAI Clinical
              </h1>
              <p className="text-[11px] font-mono font-medium text-cyan-400 print:text-slate-600 uppercase tracking-wider">
                AI-assisted retinal screening report
              </p>
            </div>
          </div>
          <div className="text-right text-xs text-slate-400 print:text-slate-600 space-y-0.5 font-mono">
            <p className="font-bold text-white print:text-slate-900">{organisation}</p>
            <p>
              Report ID:{' '}
              <span className="text-cyan-400 print:text-slate-900">
                {screening._id.slice(-8).toUpperCase()}
              </span>
            </p>
            <p>{screenedOn}</p>
          </div>
        </div>

        {/* Patient details */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 p-5 bg-slate-900/80 print:bg-slate-50 rounded-2xl border border-slate-800 print:border-slate-200 text-xs">
          <Field label="Patient" value={patient.name} />
          <Field label="Patient ID" value={patient.patientId} mono />
          <Field
            label="Age / Sex"
            value={patient.age ? `${patient.age} yrs · ${patient.gender || '—'}` : null}
          />
          <Field label="Contact" value={patient.phone} mono />
          <Field
            label="Location"
            value={[patient.village, patient.district].filter(Boolean).join(', ')}
          />
          <Field label="Diabetes duration" value={patient.diabetesDuration} />
          <Field label="Eye" value={screening.eyeSide} />
          <Field label="Model version" value={screening.modelVersion} mono />
        </div>

        {/* Assessment */}
        {isUngradable ? (
          <div className="p-6 rounded-3xl border-2 border-amber-500/40 print:border-slate-900 bg-slate-900 print:bg-white space-y-2">
            <p className="text-xs font-mono font-bold text-amber-400 print:text-slate-700 uppercase tracking-wider">
              No AI classification
            </p>
            <p className="text-2xl font-black text-white print:text-slate-900">
              Image not gradable
            </p>
            <p className="text-xs text-slate-300 print:text-slate-700 border-t border-slate-800 print:border-slate-300 pt-3 leading-relaxed">
              The retinal image did not meet the quality threshold required for reliable
              analysis, so no severity was assigned. A repeat capture is required.
              {quality.issues?.length > 0 && ` Reported issues: ${quality.issues.join('; ')}.`}
            </p>
          </div>
        ) : (
          <div className="p-6 rounded-3xl border-2 border-cyan-500/30 print:border-slate-900 bg-slate-900 print:bg-white space-y-3 shadow-xl">
            <div className="flex flex-wrap items-center justify-between gap-2">
              <div>
                <p className="text-xs font-mono font-bold text-cyan-400 print:text-slate-700 uppercase tracking-wider">
                  AI screening classification
                </p>
                <p className="text-3xl font-black mt-0.5 text-white print:text-slate-900">
                  {screening.prediction}
                </p>
              </div>
              <div className="text-right">
                <span className="text-xs px-3 py-1 rounded-full font-bold bg-white text-slate-950 print:border print:border-slate-900 uppercase font-mono">
                  {riskMeta.riskLabel}
                </span>
                <p className="text-xs text-slate-400 print:text-slate-600 mt-1 font-mono">
                  Model confidence:{' '}
                  <strong className="text-cyan-400 print:text-slate-900">
                    {screening.confidence == null
                      ? 'not recorded'
                      : `${Math.round(screening.confidence * 100)}%`}
                  </strong>
                </p>
              </div>
            </div>

            {uncertainty.reviewRequired && (
              <p className="text-xs text-amber-300 print:text-amber-900 bg-amber-950/30 print:bg-amber-50 border border-amber-500/30 print:border-amber-300 rounded-xl px-3 py-2 leading-relaxed">
                <strong>Prediction uncertain.</strong>{' '}
                {uncertainty.message ||
                  'The model could not clearly separate the top two severity classes. Specialist review is recommended.'}
              </p>
            )}

            <p className="text-xs text-slate-300 print:text-slate-700 border-t border-slate-800 print:border-slate-300 pt-3">
              <strong>Clinical guidance:</strong> {riskMeta.referralNote}
            </p>
          </div>
        )}

        {/* Images */}
        <div className="space-y-3">
          <h2 className="text-xs font-mono font-bold uppercase tracking-wider text-slate-400 print:text-slate-700">
            Retinal fundus image and AI attention map
          </h2>
          <div className="grid grid-cols-2 gap-4">
            <ImagePanel
              url={originalUrl}
              alt="Retinal fundus photograph"
              caption="Original fundus image"
              emptyText="No image on record"
            />
            {/* The real Grad-CAM output, or an honest statement that there
                isn't one. Never a generated stand-in. */}
            <ImagePanel
              url={heatmapUrl}
              alt="Grad-CAM attention map"
              caption="AI attention map (Grad-CAM)"
              emptyText="Attention map not available"
              accent
            />
          </div>
          {heatmapUrl && (
            <p className="text-[11px] text-slate-400 print:text-slate-600 leading-relaxed">
              Warm regions indicate where the model&apos;s activation was strongest for this
              classification. This is not a lesion map and does not identify specific
              abnormalities.
            </p>
          )}
        </div>

        {/* Probabilities */}
        {!isUngradable && (
          <div className="space-y-2">
            <h2 className="text-xs font-mono font-bold uppercase tracking-wider text-slate-400 print:text-slate-700">
              Class probability distribution
            </h2>
            <div className="grid grid-cols-5 gap-2 text-center text-xs">
              {PROBABILITY_ROWS.map(({ key, label }) => {
                const value = prob[key];
                const isTop = label === screening.prediction || label.startsWith(screening.prediction || '~');
                return (
                  <div
                    key={key}
                    className={`bg-slate-900 print:bg-slate-50 border rounded-xl p-2.5 ${
                      isTop
                        ? 'border-cyan-500/50 print:border-slate-900'
                        : 'border-slate-800 print:border-slate-200'
                    }`}
                  >
                    <p className="text-[10px] text-slate-400 print:text-slate-500">{label}</p>
                    <p className="font-mono font-bold text-white print:text-slate-900 mt-1">
                      {value == null ? '—' : `${(value * 100).toFixed(1)}%`}
                    </p>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* Image quality */}
        {quality.score != null && (
          <div className="space-y-2">
            <h2 className="text-xs font-mono font-bold uppercase tracking-wider text-slate-400 print:text-slate-700">
              Image quality assessment
            </h2>
            <div className="flex flex-wrap gap-x-6 gap-y-1 text-xs text-slate-300 print:text-slate-700">
              <span>
                Score: <strong>{Math.round(quality.score * 100)}%</strong>
              </span>
              <span>
                Gradable: <strong>{quality.gradable === false ? 'No' : 'Yes'}</strong>
              </span>
              {quality.issues?.length > 0 && <span>Issues: {quality.issues.join('; ')}</span>}
            </div>
          </div>
        )}

        {/* Disclaimer */}
        <div className="border border-amber-500/30 print:border-amber-400 bg-amber-950/20 print:bg-amber-50 rounded-2xl p-4 text-xs text-amber-300 print:text-amber-900 flex items-start gap-3">
          <AlertTriangle className="w-5 h-5 text-amber-400 print:text-amber-700 shrink-0 mt-0.5" />
          <div className="space-y-1">
            <p className="font-bold">Medical disclaimer</p>
            <p className="leading-relaxed text-[11px]">
              This report was produced by an AI screening tool to assist health workers. It is
              not a diagnosis. The model has not been clinically validated. Final diagnosis,
              dilated examination and treatment planning must be carried out by a qualified
              ophthalmologist.
            </p>
          </div>
        </div>

        {/* Signature */}
        <div className="pt-8 flex justify-between items-end text-xs text-slate-400 print:text-slate-500 border-t border-slate-800 print:border-slate-300">
          <div>
            <p className="font-semibold text-slate-300 print:text-slate-700">
              Screening record {screening._id}
            </p>
            <p className="font-mono text-[10px]">
              Model {screening.modelVersion || 'not recorded'}
              {screening.processingTimeMs ? ` · ${screening.processingTimeMs} ms` : ''}
            </p>
          </div>
          <div className="text-right">
            <div className="w-48 border-b border-slate-700 print:border-slate-400 mb-1.5" />
            <p className="font-semibold text-slate-300 print:text-slate-800">
              Examining clinician signature
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

function Field({ label, value, mono = false }) {
  return (
    <div>
      <p className="text-slate-400 print:text-slate-500 uppercase tracking-wide text-[10px]">
        {label}
      </p>
      <p className={`font-bold text-white print:text-slate-900 mt-0.5 ${mono ? 'font-mono' : ''}`}>
        {value || '—'}
      </p>
    </div>
  );
}

function ImagePanel({ url, alt, caption, emptyText, accent = false }) {
  return (
    <div className="border border-slate-800 print:border-slate-300 rounded-2xl overflow-hidden p-2 text-center bg-black print:bg-white">
      {url ? (
        <img src={url} alt={alt} className="max-h-56 mx-auto object-contain rounded-xl" />
      ) : (
        <div className="h-56 flex flex-col items-center justify-center gap-2 text-slate-500 print:text-slate-400">
          <ImageOff className="w-6 h-6" />
          <span className="text-[11px]">{emptyText}</span>
        </div>
      )}
      <p
        className={`text-[11px] font-mono font-semibold mt-2 ${
          accent ? 'text-cyan-400 print:text-slate-700' : 'text-slate-400 print:text-slate-600'
        }`}
      >
        {caption}
      </p>
    </div>
  );
}
