import { AlertTriangle, FlaskConical, ImageOff, HelpCircle } from 'lucide-react';

/**
 * Warning banners that sit above a screening result.
 *
 * Rendered in severity order, most serious first. Each one corresponds to a
 * condition the result must not be read without:
 *
 *   isMock          — the record came from the dev stub, not the model
 *   ungradable      — the image failed quality assessment; no prediction exists
 *   uncertainty     — the top two classes are close enough that the label alone
 *                     is misleading
 *
 * Returns null when there is nothing to warn about, so a clean result stays clean.
 */
export default function ScreeningAlerts({ screening }) {
  if (!screening) return null;

  const isMock = screening.isMock === true;
  const isUngradable = screening.analysisStatus === 'ungradable';
  const uncertainty = screening.uncertainty;
  const needsReview = uncertainty?.reviewRequired === true;
  const implausible = screening.imageQuality?.retinaPlausible === false;

  if (!isMock && !isUngradable && !needsReview && !implausible) return null;

  const topTwo = getTopTwo(screening.probabilities);

  return (
    <div className="space-y-3">
      {isMock && (
        <Banner
          tone="danger"
          icon={FlaskConical}
          title="Synthetic result — not a model output"
          body="This record was generated by the development stub while USE_MOCK_ML was enabled. It contains no information about this patient's retina and must not be used clinically or included in any report."
        />
      )}

      {isUngradable && (
        <Banner
          tone="warning"
          icon={ImageOff}
          title="Image quality insufficient for reliable AI analysis"
          body="The retinal image did not pass quality assessment, so no classification was produced. Please capture another image."
          detail={screening.imageQuality?.issues}
        />
      )}

      {screening.imageQuality?.retinaPlausible === false && (
        <Banner
          tone="warning"
          icon={ImageOff}
          title="This may not be a retinal fundus image"
          body="The image's colour profile does not match a typical fundus photograph. Confirm the correct image was uploaded before acting on this result. This is an automated heuristic and can be wrong in both directions."
        />
      )}

      {needsReview && !isUngradable && (
        <Banner
          tone="warning"
          icon={HelpCircle}
          title={`Prediction uncertain — ${formatLevel(uncertainty.level)} uncertainty`}
          body={
            topTwo
              ? `The model placed ${topTwo[0].label} at ${pct(topTwo[0].value)} and ${topTwo[1].label} at ${pct(topTwo[1].value)}. A margin this narrow means the severity label alone should not drive the referral decision. Specialist review is recommended.`
              : 'The model could not separate the top two severity classes clearly. Specialist review is recommended.'
          }
        />
      )}
    </div>
  );
}

function Banner({ tone, icon: Icon, title, body, detail }) {
  const tones = {
    danger: 'bg-red-950/50 border-red-500/40 text-red-100',
    warning: 'bg-amber-950/40 border-amber-500/35 text-amber-100',
  };
  const iconTones = { danger: 'text-red-400', warning: 'text-amber-400' };

  return (
    <div className={`rounded-2xl border p-4 flex items-start gap-3 ${tones[tone]}`} role="alert">
      <Icon className={`w-5 h-5 shrink-0 mt-0.5 ${iconTones[tone]}`} />
      <div className="space-y-1.5 min-w-0">
        <p className="font-bold text-sm leading-snug">{title}</p>
        <p className="text-xs leading-relaxed opacity-90">{body}</p>
        {Array.isArray(detail) && detail.length > 0 && (
          <ul className="text-xs space-y-0.5 pt-0.5 opacity-90">
            {detail.map((item) => (
              <li key={item} className="flex gap-2">
                <AlertTriangle className="w-3 h-3 shrink-0 mt-0.5" />
                <span>{item}</span>
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  );
}

const LABELS = {
  noDR: 'No DR',
  mild: 'Mild',
  moderate: 'Moderate',
  severe: 'Severe',
  proliferative: 'Proliferative DR',
};

function getTopTwo(probabilities) {
  if (!probabilities) return null;
  const entries = Object.entries(LABELS)
    .map(([key, label]) => ({ label, value: Number(probabilities[key] ?? 0) }))
    .sort((a, b) => b.value - a.value);
  return entries.length >= 2 ? entries.slice(0, 2) : null;
}

const pct = (v) => `${Math.round(v * 100)}%`;
const formatLevel = (level) => (level ? level.toLowerCase() : 'elevated');
